#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

# Set Wallpaper
feh --bg-fill $HOME/Pictures/Walls/wall1.jpg

MONITOR_LEFT=DisplayPort-2
MONITOR_RIGHT=HDMI-A-0

bspc monitor $MONITOR_LEFT -d 1 2 3 4
bspc monitor $MONITOR_RIGHT -d 5 6 7 8

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#88C0D0"
bspc config normal_border_color "#e6eef3"
bspc config active_border_color "#eceff4"
bspc config presel_feedback_color "#98C379"

bspc config focus_follows_pointer true
bspc config bottom_padding 8
bspc config top_padding 65
bspc config left_padding 8
bspc config right_padding 8
